services:

  postgres:
    image: postgres:16
    container_name: enjoy-trip-db
    environment:
      POSTGRES_DB: enjoy_trip
      POSTGRES_USER: enjoy_trip_user
      POSTGRES_PASSWORD: enjoy_trip_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - enjoy-trip-network

  minio:
    image: minio/minio
    container_name: enjoy-trip-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - enjoy-trip-network

volumes:
  postgres_data:
  minio_data:

networks:
  enjoy-trip-network:
    driver: bridge