-- 그룹 사진 갤러리 + 사용자 프로필 사진 (Part A, 홀수 버전 V17).
-- 이미지는 MinIO 미가동 환경이라 우선 DB(bytea)에 저장한다(추후 객체 스토리지 키로 교체 가능).

-- 사용자 프로필 사진
ALTER TABLE users ADD COLUMN avatar BYTEA;
ALTER TABLE users ADD COLUMN avatar_content_type VARCHAR(100);

-- 그룹 사진 갤러리(그룹당 최대 30장은 서비스에서 검증)
CREATE TABLE group_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    data BYTEA NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_group_photos_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_photos_uploader FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

CREATE INDEX idx_group_photos_group ON group_photos (group_id);
