-- 현재 통합 엔티티의 초기 기준선이다. 이후 Part A는 홀수, Part B는 짝수 버전으로 증분 변경한다.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE survey_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    dimension VARCHAR(20) NOT NULL,
    content VARCHAR(200) NOT NULL,
    is_reverse BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_survey_questions_dimension CHECK (
        dimension IN ('ACTIVITY', 'FOOD', 'PACE', 'URBAN_NATURE', 'TIME_PREF')
    )
);

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY,
    activity DOUBLE PRECISION NOT NULL,
    food DOUBLE PRECISION NOT NULL,
    pace DOUBLE PRECISION NOT NULL,
    urban_nature DOUBLE PRECISION NOT NULL,
    time_pref DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_preferences_activity CHECK (activity BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_food CHECK (food BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_pace CHECK (pace BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_urban_nature CHECK (urban_nature BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_time_pref CHECK (time_pref BETWEEN 0.0 AND 1.0)
);

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    cover_image_key VARCHAR(255),
    invite_code VARCHAR(6) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_groups_date_range CHECK (start_date <= end_date),
    CONSTRAINT ck_groups_status CHECK (status IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'DELETED'))
);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP(6) NOT NULL,
    left_at TIMESTAMP(6),
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_group_members_role CHECK (role IN ('OWNER', 'MEMBER'))
);

CREATE INDEX idx_group_members_active_user ON group_members (user_id, left_at);
CREATE INDEX idx_group_members_active_group ON group_members (group_id, left_at);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    payer_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    category VARCHAR(20) NOT NULL,
    split_type VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    paid_at DATE NOT NULL,
    source_schedule_id BIGINT,
    deleted_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_expenses_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (payer_id) REFERENCES users (id),
    CONSTRAINT fk_expenses_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_expenses_amount CHECK (amount BETWEEN 1 AND 100000000),
    CONSTRAINT ck_expenses_category CHECK (category IN ('MEAL', 'LODGING', 'TRANSPORT', 'TICKET', 'OTHER')),
    CONSTRAINT ck_expenses_split_type CHECK (split_type IN ('EQUAL', 'RATIO', 'AMOUNT'))
);

CREATE INDEX idx_expenses_group_paid_at ON expenses (group_id, paid_at DESC, id DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX idx_expenses_source_schedule ON expenses (source_schedule_id)
    WHERE source_schedule_id IS NOT NULL;

CREATE TABLE expense_splits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    owed_amount BIGINT NOT NULL,
    CONSTRAINT fk_expense_splits_expense FOREIGN KEY (expense_id) REFERENCES expenses (id),
    CONSTRAINT fk_expense_splits_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_expense_splits_owed_amount CHECK (owed_amount > 0)
);

CREATE INDEX idx_expense_splits_expense ON expense_splits (expense_id);
