CREATE TABLE settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    from_user_id BIGINT NOT NULL,
    to_user_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    sender_confirmed_at TIMESTAMP(6),
    receiver_confirmed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_settlements_group_users UNIQUE (group_id, from_user_id, to_user_id),
    CONSTRAINT fk_settlements_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_settlements_from_user FOREIGN KEY (from_user_id) REFERENCES users (id),
    CONSTRAINT fk_settlements_to_user FOREIGN KEY (to_user_id) REFERENCES users (id),
    CONSTRAINT ck_settlements_amount CHECK (amount > 0),
    CONSTRAINT ck_settlements_distinct_users CHECK (from_user_id <> to_user_id),
    CONSTRAINT ck_settlements_status CHECK (status IN ('PENDING', 'SENT', 'COMPLETED'))
);

CREATE INDEX idx_settlements_group_status ON settlements (group_id, status);
