-- Part A 도메인 테이블 (Place / Schedule / Vote / Recommend / MyPage) 및 users 탈퇴 컬럼.
-- 컨벤션은 V2 기준선을 따른다. Part A는 홀수 버전, Part B는 짝수 버전.

-- FR-AUTH-06: 계정 탈퇴 시 익명화 + soft delete 시각.
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP(6);

-- ===== Place (FR-PLACE) =====
CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_place_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    types VARCHAR(500),
    price_level VARCHAR(30),
    rating DOUBLE PRECISION,
    rating_count INTEGER,
    photo_name VARCHAR(500),
    google_maps_uri VARCHAR(500),
    phone_number VARCHAR(50),
    opening_hours VARCHAR(2000),
    website_uri VARCHAR(500),
    details_fetched_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    category_tag VARCHAR(30) NOT NULL,
    memo VARCHAR(500),
    personal_rating INTEGER,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_bookmarks_group_place UNIQUE (group_id, place_id),
    CONSTRAINT fk_bookmarks_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_bookmarks_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_bookmarks_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE INDEX idx_bookmarks_group ON bookmarks (group_id);

CREATE TABLE place_search_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR(500) NOT NULL UNIQUE,
    result_json TEXT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

-- ===== Schedule (FR-SCHEDULE) =====
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    schedule_date DATE NOT NULL,
    order_index INTEGER NOT NULL,
    start_time TIME(6) NOT NULL,
    end_time TIME(6) NOT NULL,
    memo VARCHAR(500),
    estimated_cost BIGINT,
    transport_mode VARCHAR(20),
    status VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_schedules_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_schedules_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_schedules_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_schedules_updater FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT ck_schedules_status CHECK (status IN ('PLANNED', 'VOTING', 'CANCELLED')),
    CONSTRAINT ck_schedules_transport_mode CHECK (transport_mode IS NULL OR transport_mode IN ('CAR', 'TRANSIT', 'WALK'))
);

CREATE INDEX idx_schedules_group_date_order ON schedules (group_id, schedule_date, order_index);

CREATE TABLE transport_legs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR(200) NOT NULL UNIQUE,
    mode VARCHAR(20) NOT NULL,
    available BOOLEAN NOT NULL,
    duration_seconds INTEGER,
    distance_meters INTEGER,
    toll INTEGER,
    fuel_cost INTEGER,
    taxi_fare INTEGER,
    transit_fare INTEGER,
    transfer_count INTEGER,
    route_summary VARCHAR(500),
    note VARCHAR(200),
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_transport_legs_mode CHECK (mode IN ('CAR', 'TRANSIT', 'WALK'))
);

-- ===== Vote (FR-VOTE) =====
CREATE TABLE vote_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    title VARCHAR(100),
    closes_at TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL,
    winner_candidate_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_vote_sessions_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_vote_sessions_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id),
    CONSTRAINT fk_vote_sessions_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_vote_sessions_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE TABLE vote_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_session_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    registered_by BIGINT NOT NULL,
    memo VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_vote_candidates_session FOREIGN KEY (vote_session_id) REFERENCES vote_sessions (id),
    CONSTRAINT fk_vote_candidates_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_vote_candidates_registrant FOREIGN KEY (registered_by) REFERENCES users (id)
);

CREATE INDEX idx_vote_candidates_session ON vote_candidates (vote_session_id);

CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    voter_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_votes_candidate_voter UNIQUE (candidate_id, voter_id),
    CONSTRAINT fk_votes_candidate FOREIGN KEY (candidate_id) REFERENCES vote_candidates (id),
    CONSTRAINT fk_votes_voter FOREIGN KEY (voter_id) REFERENCES users (id),
    CONSTRAINT ck_votes_score CHECK (score BETWEEN 1 AND 5)
);

-- ===== Recommend (FR-RECOMMEND) =====
CREATE TABLE recommendation_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR(100) NOT NULL UNIQUE,
    result_json TEXT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

-- ===== MyPage 회고 (FR-MYPAGE-04) =====
CREATE TABLE retrospectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content VARCHAR(200) NOT NULL,
    rating INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_retrospectives_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_retrospectives_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_retrospectives_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_retrospectives_rating CHECK (rating BETWEEN 1 AND 5)
);
