-- OAuth 공급자 계정과 내부 사용자 계정을 분리해 한 사용자가 여러 로그인 방식을 안전하게 연결할 수 있게 한다.
CREATE TABLE oauth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_oauth_identities_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_oauth_identities_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_oauth_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_oauth_identities_provider CHECK (provider IN ('GOOGLE', 'KAKAO'))
);

CREATE INDEX idx_oauth_identities_user ON oauth_identities (user_id);
