-- 그룹 여행 계획 - 숙소 선정/예약 (Part A, 홀수 버전).
-- V7까지 사용 중이라 다음 홀수 V9를 사용한다(V8은 Part B 예약).
-- 숙소는 Google Places(lodging) 단일 소스에서 선정하며, 예약완료 사진은 MinIO 미가동 환경이라
-- 우선 DB(bytea)에 저장한다(추후 객체 스토리지 키로 교체 가능).

CREATE TABLE group_accommodations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    sigungu VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    reservation_price BIGINT,
    booking_photo BYTEA,
    booking_photo_content_type VARCHAR(100),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_group_acc_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_acc_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_group_acc_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_group_acc_status CHECK (status IN ('SELECTED', 'BOOKED'))
);

CREATE INDEX idx_group_acc_group ON group_accommodations (group_id);
