-- ============================================================================
-- 그룹 여행 협업 플랫폼 (enjoy-trip) — DB Schema (PostgreSQL 16)
-- ----------------------------------------------------------------------------
-- 이 파일은 산출물 제출용 "통합 스키마(최종 상태)"이다.
-- 운영 원천(Source of Truth)은 Flyway 마이그레이션:
--   backend/src/main/resources/db/migration/V2 ~ V29
-- 아래 DDL은 모든 마이그레이션을 적용한 최종 형태를 한 파일로 정리한 것이다.
-- 초기 데이터(설문 문항·테스트 계정)는 애플리케이션 기동 시 DataInitializer가 시드한다.
-- ============================================================================

-- ===================== 인증 / 계정 =====================
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL UNIQUE,
    password            VARCHAR(255) NOT NULL,           -- 소셜 전용 전환 후 placeholder
    name                VARCHAR(255) NOT NULL,
    avatar_key          VARCHAR(255),                    -- S3 object key
    avatar_content_type VARCHAR(100),
    payout_link         VARCHAR(512),                    -- AES-GCM 암호문(Base64)
    payout_account      VARCHAR(512),                    -- AES-GCM 암호문(Base64)
    deleted_at          TIMESTAMP(6),                    -- 탈퇴 익명화 soft delete
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL
);

CREATE TABLE oauth_identities (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    provider         VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_oauth_identities_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_oauth_identities_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_oauth_identities_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_oauth_identities_provider CHECK (provider IN ('GOOGLE', 'KAKAO'))
);
CREATE INDEX idx_oauth_identities_user ON oauth_identities (user_id);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    token      VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

-- ===================== 성향 설문 =====================
CREATE TABLE survey_questions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(10) NOT NULL UNIQUE,
    dimension     VARCHAR(20) NOT NULL,
    content       VARCHAR(200) NOT NULL,
    is_reverse    BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_survey_questions_dimension CHECK (
        dimension IN ('ACTIVITY', 'FOOD', 'PACE', 'URBAN_NATURE', 'TIME_PREF')
    )
);

CREATE TABLE user_preferences (
    user_id      BIGINT PRIMARY KEY,
    activity     DOUBLE PRECISION NOT NULL,
    food         DOUBLE PRECISION NOT NULL,
    pace         DOUBLE PRECISION NOT NULL,
    urban_nature DOUBLE PRECISION NOT NULL,
    time_pref    DOUBLE PRECISION NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_preferences_activity     CHECK (activity     BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_food         CHECK (food         BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_pace         CHECK (pace         BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_urban_nature CHECK (urban_nature BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_user_preferences_time_pref    CHECK (time_pref    BETWEEN 0.0 AND 1.0)
);

-- ===================== 그룹 =====================
CREATE TABLE groups (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                    VARCHAR(30) NOT NULL,
    destination              VARCHAR(100) NOT NULL,
    start_date               DATE NOT NULL,
    end_date                 DATE NOT NULL,
    cover_image_key          VARCHAR(255),     -- 프리셋 식별자 또는 'CUSTOM'
    cover_object_key         VARCHAR(255),     -- 커스텀 커버 S3 key
    cover_image_content_type VARCHAR(100),
    invite_code              VARCHAR(6) NOT NULL UNIQUE,
    status                   VARCHAR(20) NOT NULL,
    deleted_at               TIMESTAMP(6),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_groups_date_range CHECK (start_date <= end_date),
    CONSTRAINT ck_groups_status CHECK (status IN ('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'DELETED'))
);

CREATE TABLE group_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id  BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    role      VARCHAR(20) NOT NULL,
    joined_at TIMESTAMP(6) NOT NULL,
    left_at   TIMESTAMP(6),
    CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_group_members_role CHECK (role IN ('OWNER', 'MEMBER'))
);
CREATE INDEX idx_group_members_active_user  ON group_members (user_id, left_at);
CREATE INDEX idx_group_members_active_group ON group_members (group_id, left_at);

CREATE TABLE group_photos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     BIGINT NOT NULL,
    uploaded_by  BIGINT NOT NULL,
    object_key   VARCHAR(255) NOT NULL,   -- S3 key (구버전 bytea → V21에서 전환)
    content_type VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_group_photos_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_photos_uploader FOREIGN KEY (uploaded_by) REFERENCES users (id)
);
CREATE INDEX idx_group_photos_group ON group_photos (group_id);

-- ===================== 장소 =====================
CREATE TABLE places (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_place_id    VARCHAR(255) NOT NULL UNIQUE,
    name               VARCHAR(255) NOT NULL,
    address            VARCHAR(500),
    latitude           DOUBLE PRECISION NOT NULL,
    longitude          DOUBLE PRECISION NOT NULL,
    types              VARCHAR(500),
    price_level        VARCHAR(30),
    rating             DOUBLE PRECISION,
    rating_count       INTEGER,
    photo_name         VARCHAR(500),
    google_maps_uri    VARCHAR(500),
    phone_number       VARCHAR(50),
    opening_hours      VARCHAR(2000),
    website_uri        VARCHAR(500),
    details_fetched_at TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL
);

CREATE TABLE bookmarks (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT NOT NULL,
    place_id        BIGINT NOT NULL,
    created_by      BIGINT NOT NULL,
    category_tag    VARCHAR(30) NOT NULL,
    memo            VARCHAR(500),
    personal_rating INTEGER,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_bookmarks_group_place UNIQUE (group_id, place_id),
    CONSTRAINT fk_bookmarks_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_bookmarks_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_bookmarks_creator FOREIGN KEY (created_by) REFERENCES users (id)
);
CREATE INDEX idx_bookmarks_group ON bookmarks (group_id);

CREATE TABLE place_search_cache (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key  VARCHAR(500) NOT NULL UNIQUE,
    result_json TEXT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

-- ===================== 일정 / 이동 / 숙소 =====================
CREATE TABLE schedules (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id       BIGINT NOT NULL,
    place_id       BIGINT,                       -- nullable: 빈 일정(투표로 결정) 허용
    title          VARCHAR(100),                 -- 빈 일정 제목
    schedule_date  DATE NOT NULL,
    order_index    INTEGER NOT NULL,
    start_time     TIME(6) NOT NULL,
    end_time       TIME(6) NOT NULL,
    memo           VARCHAR(500),
    estimated_cost BIGINT,
    transport_mode VARCHAR(20),
    status         VARCHAR(20) NOT NULL,
    created_by     BIGINT NOT NULL,
    updated_by     BIGINT NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_schedules_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_schedules_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_schedules_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_schedules_updater FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT ck_schedules_status CHECK (status IN ('PLANNED', 'VOTING', 'CANCELLED')),
    CONSTRAINT ck_schedules_transport_mode CHECK (transport_mode IS NULL OR transport_mode IN ('CAR', 'TRANSIT', 'WALK'))
);
CREATE INDEX idx_schedules_group_date_order ON schedules (group_id, schedule_date, order_index);

CREATE TABLE transport_legs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key        VARCHAR(200) NOT NULL UNIQUE,
    mode             VARCHAR(20) NOT NULL,
    available        BOOLEAN NOT NULL,
    duration_seconds INTEGER,
    distance_meters  INTEGER,
    toll             INTEGER,
    fuel_cost        INTEGER,
    taxi_fare        INTEGER,
    transit_fare     INTEGER,
    transfer_count   INTEGER,
    route_summary    VARCHAR(500),
    note             VARCHAR(200),
    expires_at       TIMESTAMP(6) NOT NULL,      -- 1시간 캐시
    created_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT ck_transport_legs_mode CHECK (mode IN ('CAR', 'TRANSIT', 'WALK'))
);

CREATE TABLE group_accommodations (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id                   BIGINT NOT NULL,
    place_id                   BIGINT NOT NULL,
    created_by                 BIGINT NOT NULL,
    sigungu                    VARCHAR(100),
    status                     VARCHAR(20) NOT NULL,
    reservation_price          BIGINT,
    booking_photo_key          VARCHAR(255),      -- S3 key (V21 전환)
    booking_photo_content_type VARCHAR(100),
    stay_date                  DATE,              -- 체크인
    stay_end_date              DATE,              -- 체크아웃(여러 박)
    created_at                 TIMESTAMP(6) NOT NULL,
    updated_at                 TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_group_acc_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_group_acc_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_group_acc_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_group_acc_status CHECK (status IN ('SELECTED', 'BOOKED'))
);
CREATE INDEX idx_group_acc_group      ON group_accommodations (group_id);
CREATE INDEX idx_group_acc_group_date ON group_accommodations (group_id, stay_date);

-- ===================== 투표 =====================
CREATE TABLE vote_sessions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id            BIGINT NOT NULL,
    schedule_id         BIGINT NOT NULL,
    title               VARCHAR(100),
    closes_at           TIMESTAMP(6),
    status              VARCHAR(20) NOT NULL,
    created_by          BIGINT NOT NULL,
    winner_candidate_id BIGINT,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_vote_sessions_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_vote_sessions_schedule FOREIGN KEY (schedule_id) REFERENCES schedules (id),
    CONSTRAINT fk_vote_sessions_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_vote_sessions_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE TABLE vote_candidates (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_session_id BIGINT NOT NULL,
    place_id        BIGINT NOT NULL,
    registered_by   BIGINT NOT NULL,
    memo            VARCHAR(500),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_vote_candidates_session FOREIGN KEY (vote_session_id) REFERENCES vote_sessions (id),
    CONSTRAINT fk_vote_candidates_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_vote_candidates_registrant FOREIGN KEY (registered_by) REFERENCES users (id)
);
CREATE INDEX idx_vote_candidates_session ON vote_candidates (vote_session_id);

CREATE TABLE votes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    voter_id     BIGINT NOT NULL,
    score        INTEGER NOT NULL,
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_votes_candidate_voter UNIQUE (candidate_id, voter_id),
    CONSTRAINT fk_votes_candidate FOREIGN KEY (candidate_id) REFERENCES vote_candidates (id),
    CONSTRAINT fk_votes_voter FOREIGN KEY (voter_id) REFERENCES users (id),
    CONSTRAINT ck_votes_score CHECK (score BETWEEN 1 AND 5)
);

-- ===================== 비용 / 정산 =====================
CREATE TABLE expenses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id           BIGINT NOT NULL,
    payer_id           BIGINT NOT NULL,
    created_by         BIGINT NOT NULL,
    amount             BIGINT NOT NULL,
    category           VARCHAR(20) NOT NULL,
    split_type         VARCHAR(20) NOT NULL,
    description        VARCHAR(255),
    memo               VARCHAR(255),
    paid_at            DATE NOT NULL,
    source_schedule_id BIGINT,                  -- 일정→정산 자동등록 멱등키
    deleted_at         TIMESTAMP(6),
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_expenses_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (payer_id) REFERENCES users (id),
    CONSTRAINT fk_expenses_creator FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_expenses_amount CHECK (amount BETWEEN 1 AND 100000000),
    CONSTRAINT ck_expenses_category CHECK (category IN ('MEAL', 'LODGING', 'TRANSPORT', 'TICKET', 'OTHER')),
    CONSTRAINT ck_expenses_split_type CHECK (split_type IN ('EQUAL', 'RATIO', 'AMOUNT'))
);
CREATE INDEX idx_expenses_group_paid_at ON expenses (group_id, paid_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_expenses_source_schedule ON expenses (source_schedule_id) WHERE source_schedule_id IS NOT NULL;

CREATE TABLE expense_splits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id  BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    owed_amount BIGINT NOT NULL,
    CONSTRAINT fk_expense_splits_expense FOREIGN KEY (expense_id) REFERENCES expenses (id),
    CONSTRAINT fk_expense_splits_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_expense_splits_owed_amount CHECK (owed_amount > 0)
);
CREATE INDEX idx_expense_splits_expense ON expense_splits (expense_id);

CREATE TABLE settlements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id             BIGINT NOT NULL,
    from_user_id         BIGINT NOT NULL,
    to_user_id           BIGINT NOT NULL,
    amount               BIGINT NOT NULL,
    status               VARCHAR(20) NOT NULL,
    sender_confirmed_at  TIMESTAMP(6),
    receiver_confirmed_at TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_settlements_group_users UNIQUE (group_id, from_user_id, to_user_id),
    CONSTRAINT fk_settlements_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_settlements_from_user FOREIGN KEY (from_user_id) REFERENCES users (id),
    CONSTRAINT fk_settlements_to_user FOREIGN KEY (to_user_id) REFERENCES users (id),
    CONSTRAINT ck_settlements_amount CHECK (amount > 0),
    CONSTRAINT ck_settlements_distinct_users CHECK (from_user_id <> to_user_id),
    CONSTRAINT ck_settlements_status CHECK (status IN ('PENDING', 'SENT', 'COMPLETED'))
);
CREATE INDEX idx_settlements_group_status ON settlements (group_id, status);

-- ===================== 알림 / 추천 / 회고 =====================
CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    type         VARCHAR(40) NOT NULL,
    message      VARCHAR(255) NOT NULL,
    target_path  VARCHAR(255) NOT NULL,
    read_at      TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_notifications_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users (id)
);
CREATE INDEX idx_notifications_recipient_created ON notifications (recipient_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_unread  ON notifications (recipient_id, read_at) WHERE read_at IS NULL;

CREATE TABLE recommendation_cache (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key   VARCHAR(100) NOT NULL UNIQUE,
    result_json TEXT NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE retrospectives (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    content    VARCHAR(200) NOT NULL,
    rating     INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_retrospectives_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_retrospectives_group FOREIGN KEY (group_id) REFERENCES groups (id),
    CONSTRAINT fk_retrospectives_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_retrospectives_rating CHECK (rating BETWEEN 1 AND 5)
);

-- ============================================================================
-- 초기 데이터 (Seed) — 운영에서는 애플리케이션 기동 시 DataInitializer가 시드한다.
-- 아래는 동일 내용을 SQL로 표현한 참고용이다. created_at/updated_at은 now()로 대체.
-- ============================================================================

-- (1) 테스트 계정 (비밀번호는 BCrypt 해시. 평문: test1234 / 이메일: test@test.com)
-- INSERT INTO users (email, password, name, created_at, updated_at)
-- VALUES ('test@test.com', '<BCrypt-hash>', 'Test User', now(), now());

-- (2) 성향 설문 12문항 (5차원 × 코드/문항/역채점/표시순서)
INSERT INTO survey_questions (code, dimension, content, is_reverse, display_order, created_at, updated_at) VALUES
('A03','ACTIVITY','하루에 1만 보 이상 걷는 일정도 괜찮다',                    FALSE, 1,  now(), now()),
('A05','ACTIVITY','여행은 결국 쉬려고 가는 거다',                            TRUE,  2,  now(), now()),
('F01','FOOD','줄을 1시간 서더라도 유명한 맛집은 꼭 가야 한다',               FALSE, 3,  now(), now()),
('F02','FOOD','식사는 끼니만 때우면 된다',                                   TRUE,  4,  now(), now()),
('P01','PACE','시간 단위로 계획을 짜놓는 게 마음이 편하다',                   FALSE, 5,  now(), now()),
('P05','PACE','일정 사이에 비어있는 시간이 있어야 마음이 편하다',             TRUE,  6,  now(), now()),
('P07','PACE','사진 찍느라 한 장소에서 30분 이상 머무는 것도 괜찮다',         FALSE, 7,  now(), now()),
('U01','URBAN_NATURE','도시의 활기찬 분위기를 좋아한다',                     FALSE, 8,  now(), now()),
('U02','URBAN_NATURE','자연 풍경 속에 있을 때 가장 행복하다',                TRUE,  9,  now(), now()),
('T01','TIME_PREF','일출을 보러 새벽에 일어날 수 있다',                      FALSE, 10, now(), now()),
('T03','TIME_PREF','밤 늦게까지 야경이나 술 한잔을 즐기고 싶다',             TRUE,  11, now(), now()),
('T04','TIME_PREF','저녁 10시 전에는 숙소에 들어가는 게 좋다',               FALSE, 12, now(), now());

-- 끝.
