spring:
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true

auth:
  refresh-cookie-secure: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
